%macro getdata;
%LET LAST_DT=INTNX('MONTH',&STAT_DT.,-1,'END');
/*T-1月数据处理*/
/*贷款信息*/
data sino_loan;
 FORMAT OPEN_DT YYMMDD10.;
 INFORMAT OPEN_DT YYMMDD10.;
 set SSS.SINO_LOAN(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND 
                          SORGCODE not in ('Q10152900H0000' 'Q10152900H0001')));
 OPEN_DT=DATEPART(DDATEOPENED);
 OPEN_DUR=INTCK('MONTH',OPEN_DT,&STAT_DT.);
 OPEN_DUR_CD=PUT(OPEN_DUR,OPEN_LEVEL.);
 IF OPEN_DUR=-3 THEN OPEN_DUR=0;
 IF SLOANTYPE='13' THEN SLOANTYPE='11';
 AMT_CD=PUT(ICREDITLIMIT,PAY_AMT_level.);
 PROV_CD=PUT(SUBSTR(SAREACODE,1,2),$PROV_LEVEL.);
 REPAY_CD=PUT(SMONTHDURATION,$REPAYDUR_level.);
/*REPAY_CD为中间字段，用于生成还款期限的划分*/
 IF REPAY_CD ='0' THEN REPAY_CD = '1';
 ORGAREA=PUT(SORGCODE,$ORGAREA_CD.);
 SHORT_NM=PUT(SORGCODE,$SHORT_CD.);
run;
PROC SORT DATA=sino_loan(where=(datepart(dgetdate)<=&stat_dt.));
	BY SORGCODE SACCOUNT DGETDATE;
RUN;
DATA LOAN_N;
	SET sino_loan;
	BY SORGCODE SACCOUNT DGETDATE;
	IF LAST.SACCOUNT;
RUN;

/*申请信息*/
data sino_loan_apply;
 set SSS.SINO_LOAN_APPLY(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND 
                                SORGCODE not in ('Q10152900H0000' 'Q10152900H0001')));
run;
PROC SORT DATA=sino_loan_apply(where=(DATEPART(DGETDATE) <= &STAT_DT.));
	BY SORGCODE SAPPLYCODE SCERTNO;
RUN;
DATA APPLY_N1;
	SET sino_loan_apply;
	BY SORGCODE SAPPLYCODE SCERTNO;
	IF LAST.SCERTNO;
RUN;
DATA APPLY_N;
	SET APPLY_N1;
	ORGAREA=PUT(SORGCODE,$ORGAREA_CD.);
RUN;

/*特殊交易信息*/
data sino_loan_spec_trade;
 set SSS.Sino_LOAN_SPEC_TRADE(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND 
                                     SORGCODE not in ('Q10152900H0000' 'Q10152900H0001')));
run;
PROC SORT DATA=sino_loan_spec_trade(where=(DATEPART(DGETDATE) <= &STAT_DT.));
	BY SORGCODE SACCOUNT;
RUN;
DATA SPEC_N1;
	SET sino_loan_spec_trade;
	BY SORGCODE SACCOUNT;
	IF LAST.SACCOUNT;
RUN;
DATA SPEC_N;
	SET SPEC_N1;
	ORGAREA=PUT(SORGCODE,$ORGAREA_CD.);
RUN;

data sino_person_certification;
 set SSS.Sino_person_certification(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND 
                                          SORGCODE^='Q10152900H0000' AND SORGCODE^='Q10152900H0001'));
run;
PROC SORT DATA=sino_person_certification(where=(DATEPART(DGETDATE)<=&STAT_DT.))  OUT=SINO_PERSON_CERT_n1;
	BY SCERTNO DGETDATE;
RUN;
DATA SINO_PERSON_CERT_n;
	SET SINO_PERSON_CERT_n1;
	BY SCERTNO DGETDATE;
	IF LAST.SCERTNO;
RUN;

data sino_person;
 set SSS.Sino_person(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND 
                            SORGCODE^='Q10152900H0000' AND SORGCODE^='Q10152900H0001'));
run;
PROC SORT DATA=sino_person(where=(DATEPART(DGETDATE)<=&STAT_DT.))  OUT=SINO_PERSON_n1;
	BY spin DGETDATE;
RUN;
DATA SINO_PERSON_n;
	SET SINO_PERSON_n1;
	BY spin DGETDATE;
	IF LAST.spin;
RUN;

/*T-2月数据处理*/
/*贷款信息*/
PROC SORT DATA=sino_loan(where=(DATEPART(DGETDATE) <= &LAST_DT.)) OUT=LOAN_O1 ;
	BY SORGCODE SACCOUNT DGETDATE;
RUN;

DATA LOAN_O;
	SET LOAN_O1;
	BY SORGCODE SACCOUNT DGETDATE;
	IF LAST.SACCOUNT;
RUN;

/*申请信息*/
PROC SORT DATA=sino_loan_apply(where=(DATEPART(DGETDATE) <= &LAST_DT.)) OUT= APPLY_O1;
	BY SORGCODE SAPPLYCODE SCERTNO;
RUN;

DATA APPLY_O2;
	SET APPLY_O1;
	BY SORGCODE SAPPLYCODE SCERTNO;
	IF LAST.SCERTNO;
RUN;
DATA APPLY_O;
	SET APPLY_O2;
	ORGAREA=PUT(SORGCODE,$ORGAREA_CD.);
RUN;

/*特殊交易信息*/
PROC SORT DATA=sino_loan_spec_trade(where=(DATEPART(DGETDATE) <= &LAST_DT.)) OUT=SPEC_O1;
	BY SORGCODE SACCOUNT;
RUN;
DATA SPEC_O2;
	SET SPEC_O1;
	BY SORGCODE SACCOUNT;
	IF LAST.SACCOUNT;
RUN;
DATA SPEC_O;
	SET SPEC_O2;
	ORGAREA=PUT(SORGCODE,$ORGAREA_CD.);
RUN;


/*本月(T-1)数据处理 去重处理并取最新一条*/

/*上月(T-2)数据处理 去重处理并取最新一条*/
/*data sino_person_certification_o;*/
/* set SSS.Sino_person_certification(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND */
/*                                          SORGCODE^='Q10152900H0000' AND SORGCODE^='Q10152900H0001' AND */
/*                                          DATEPART(DGETDATE)<=&LAST_DT.));*/
/*run;*/
PROC SORT DATA=sino_person_certification(where=(DATEPART(DGETDATE)<=&LAST_DT.))  OUT=SINO_PERSON_CERT_O1;
	BY SCERTNO DGETDATE;
RUN;
DATA SINO_PERSON_CERT_o;
	SET SINO_PERSON_CERT_O1;
	BY SCERTNO DGETDATE;
	IF LAST.SCERTNO;
RUN;

/*data sino_person_o;*/
/* set SSS.Sino_person(WHERE=(SUBSTR(SORGCODE,1,1)='Q' AND */
/*                            SORGCODE^='Q10152900H0000' AND SORGCODE^='Q10152900H0001' AND */
/*                            DATEPART(DGETDATE)<=&LAST_DT.));*/
/*run;*/
PROC SORT DATA=sino_person(where=(DATEPART(DGETDATE)<=&LAST_DT.))  OUT=SINO_PERSON_O1;
	BY spin DGETDATE;
RUN;
DATA SINO_PERSON_o;
	SET SINO_PERSON_o1;
	BY spin DGETDATE;
	IF LAST.spin;
RUN;
%mend getdata;
